export enum EStatusEquipment {
  OPERATIVO_BUENO = "OPERATIVO BUENO",
  OPERATIVO_REGULAR = "OPERATIVO REGULAR",
  INOPERATIVO_POR_REPARAR = "INOPERATIVO POR REPARAR",
  INOPERATIVO_PARA_BAJA = "INOPERATIVO PARA BAJA",
  MALO_POR_REPARAR = "MALO POR REPARAR",
  MALO_PARA_BAJA = "MALO PARA BAJA",
}
